# The JOURNAL_MACRO_TO_NAME must match the defined macros (@string) in your
# bibtex file
#
# r !./get_macros_as_dict.py refs.bib
JOURNAL_MACRO_TO_NAME = {
    'aamop': 'Adv. At. Mol. Opt. Phys.',
    'aarc': 'Autom. Rem. Contr.',
    'ac': 'Anal. Chem.',
    'acie': 'Angew. Chem. Int. Ed.',
    'aipa': 'AIP Advances',
    'ajp': 'Am. J. Phys.',
    'algo': 'Algorithmica',
    'ao': 'Appl. Opt.',
    'ap': 'Adv. Phys.',
    'apb': 'Appl. Phys. B',
    'apl': 'Appl. Phys. Lett.',
    'apx': 'Adv. Phys. X',
    'aqt': 'Adv. Quantum Tech.',
    'arcmp': 'Annu. Rev. Condens. Matter Phys.',
    'arpc': 'Annu. Rev. Phys. Chem.',
    'astrocomp': 'Astron. Comput.',
    'atms': 'ACM Trans. Math. Softw.',
    'avsqs': 'AVS Quantum Sci.',
    'bit': 'BIT',
    'bstj': 'Bell System Tech. J.',
    'cacm': 'Commun. ACM',
    'ccyb': 'Control Cybern.',
    'cmp': 'Commun. Math. Phys.',
    'computj': 'Comput. J.',
    'contp': 'Contemp. Phys.',
    'cp': 'Chem. Phys.',
    'cpam': 'Commun. Pur. Appl. Math.',
    'cpc': 'Comput. Phys. Commun.',
    'cpl': 'Chem. Phys. Lett.',
    'cse': 'Comput. Sci. Eng.',
    'csj': 'CEAS Space J.',
    'ecyb': 'Engrg. Cybernetics',
    'ejc': 'Eur. J. Control',
    'ejp': 'Eur. J. Phys.',
    'electr': 'Electronics',
    'entr': 'Entropy',
    'epjb': 'Eur. Phys. J. B',
    'epjd': 'Eur. Phys. J. D',
    'epjp': 'Eur. Phys. J. Plus',
    'epjqt': 'EPJ Quantum Technol.',
    'epl': 'Europhys. Lett.',
    'farad': 'Faraday Disc.',
    'foundphys': 'Found. Phys.',
    'fp': 'Fortschr. Phys.',
    'icta': 'IET Control Theory Appl.',
    'ijqe': 'IEEE J. Quantum Electron.',
    'ijqi': 'Int. J. Quantum Inform.',
    'ijtp': 'Int. J. Theor. Phys.',
    'imajam': 'IMA J. Appl. Math.',
    'ip': 'Inverse Problems',
    'irpc': 'Int. Rev. Phys. Chem.',
    'itac': 'IEEE Trans. Automat. Contr.',
    'itas': 'IEEE Trans. on Appl. Superc.',
    'jap': 'J. Appl. Phys.',
    'jcam': 'J. Comput. Appl. Math',
    'jcmpp': 'J. Comput. Phys.',
    'jcp': 'J. Chem. Phys.',
    'jcpm': 'J. Phys. Condens. Matter',
    'jcss': 'J. Comput. System Sci.',
    'jctn': 'J. Comput. Theor. Nanos.',
    'jlum': 'J. Lumin.',
    'jmo': 'J. Mod. Opt.',
    'jmp': 'J. Math. Phys.',
    'jmr': 'J. Magnet. Res.',
    'jmra': 'J. Magnet. Res. A',
    'job': 'J. Optics B',
    'jors': 'J. Open Res. Softw.',
    'josab': 'J. Opt. Soc. Am. B',
    'joss': 'J. Open Source Softw.',
    'jota': 'J. Optim. Theor. Appl.',
    'jpa': 'J. Phys. A',
    'jpamt': 'J. Phys. A: Math. Theor.',
    'jpb': 'J. Phys. B',
    'jpc': 'J. Phys. Chem.',
    'jpca': 'J. Phys. Chem. A',
    'jpcm': 'J. Phys.: Condens. Matter',
    'jsp': 'J .Stat. Phys.',
    'mc': 'Math. Comput.',
    'mlst': 'Mach. Learn.: Sci. Technol.',
    'nams': 'Notices Amer. Math. Soc.',
    'nat': 'Nature',
    'natcom': 'Nat. Commun.',
    'natmeth': 'Nat. Methods',
    'natnano': 'Nat. Nano.',
    'natphot': 'Nat. Photon.',
    'natphys': 'Nat. Phys.',
    'njp': 'New J. Phys.',
    'npjqi': 'npj Quantum Inf',
    'nrp': 'Nat. Rev. Phys.',
    'oc': 'Opt. Comm.',
    'oe': 'Opt. Express',
    'os': 'Opt. Spectr.',
    'physd': 'Physica D',
    'physrep': 'Phys. Rep.',
    'pire': 'Proc. IRE',
    'pl': 'Phys. Lett.',
    'pla': 'Phys. Lett. A',
    'plms': 'Proc. Lond. Math. Soc.',
    'pnas': 'Proc. Natl. Acad. Sci. U.S.A',
    'pr': 'Phys. Rev.',
    'pra': 'Phys. Rev. A',
    'prapl': 'Phys. Rev. Applied',
    'prb': 'Phys. Rev. B',
    'prc': 'Phys. Rev. C',
    'prd': 'Phys. Rev. D',
    'pre': 'Phys. Rev. E',
    'prl': 'Phys. Rev. Lett.',
    'prr': 'Phys. Rev. Research',
    'prsa': 'Proc. R. Soc. A',
    'prx': 'Phys. Rev. X',
    'prxq': 'PRX Quantum',
    'ps': 'Phys. Scripta',
    'pt': 'Phys. Today',
    'ptrsa': 'Phil. Trans. R. Soc. A',
    'qam': 'Q. Appl. Math.',
    'qic': 'Quantum Info. Comput.',
    'qip': 'Quantum Inf. Process.',
    'qso': 'Quantum Semiclass. Opt.',
    'qst': 'Quantum Sci. Technol.',
    'quant': 'Quantum',
    'rmp': 'Rev. Mod. Phys.',
    'rms': 'Russ. Math. Surv.',
    'rpp': 'Rep. Prog. Phys.',
    'rsi': 'Rev. Sci. Instr.',
    'sb': 'Sci. Bull.',
    'sci': 'Science',
    'sciam': 'Sci. Am.',
    'scis': 'Sci. China Inf. Sci.',
    'siamjc': 'SIAM J. Comput.',
    'siamjsc': 'SIAM J. Sci. Comput.',
    'siamrev': 'SIAM Rev.',
    'sp': 'Sig. Process.',
    'spp': 'SciPost Phys.',
    'sr': 'Sci. Rep.',
    'sst': 'Supercond. Sci. Technol.',
    'widm': 'WIREs Data Mining Knowl Discov.',
    'zp': 'Z. Phys.',
}


# JOURNAL_NAME_TO_MACRO is the inverse mapping of JOURNAL_MACRO_TO_NAME...
JOURNAL_NAME_TO_MACRO = {
    val: key for (key, val) in JOURNAL_MACRO_TO_NAME.items()
}
# ... with some aliases:
JOURNAL_NAME_TO_MACRO.update(
    {
        'J. Phys. B: At. Mol. Opt. Phys.': 'jpb',
        'The Journal of Chemical Physics': 'jcp',
    }
)

# In most cases, we get the journal initials simply by taking all the caps from
# the name. The following are some exceptions
JOURNAL_INITIALS = {
    'ACM Trans. Math. Softw.': 'ATMS',
    'CEAS Space J.': 'CSJ',
    'IEEE Trans. on Appl. Superc.': 'ITAS',
    'IEEE Trans. Automat. Contr.': 'ITAC',
    'npj Quantum Inf': 'NPJQI',
    'SIAM J. Comput.': 'SJC',
    'SIAM J. Sci. Comput.': 'SJSC',
    'SIAM Rev.': 'SR',
}
